/* DO NOT EDIT: This file is automatically generated by Cabal */

/* package score2-0.1.0.0 */
#ifndef VERSION_score2
#define VERSION_score2 "0.1.0.0"
#endif /* VERSION_score2 */
#ifndef MIN_VERSION_score2
#define MIN_VERSION_score2(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  1 || \
  (major1) == 0 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_score2 */

/* package base-4.11.1.0 */
#ifndef VERSION_base
#define VERSION_base "4.11.1.0"
#endif /* VERSION_base */
#ifndef MIN_VERSION_base
#define MIN_VERSION_base(major1,major2,minor) (\
  (major1) <  4 || \
  (major1) == 4 && (major2) <  11 || \
  (major1) == 4 && (major2) == 11 && (minor) <= 1)
#endif /* MIN_VERSION_base */

/* package random-1.1 */
#ifndef VERSION_random
#define VERSION_random "1.1"
#endif /* VERSION_random */
#ifndef MIN_VERSION_random
#define MIN_VERSION_random(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  1 || \
  (major1) == 1 && (major2) == 1 && (minor) <= 0)
#endif /* MIN_VERSION_random */

/* package text-1.2.3.1 */
#ifndef VERSION_text
#define VERSION_text "1.2.3.1"
#endif /* VERSION_text */
#ifndef MIN_VERSION_text
#define MIN_VERSION_text(major1,major2,minor) (\
  (major1) <  1 || \
  (major1) == 1 && (major2) <  2 || \
  (major1) == 1 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_text */

/* package websockets-0.12.5.2 */
#ifndef VERSION_websockets
#define VERSION_websockets "0.12.5.2"
#endif /* VERSION_websockets */
#ifndef MIN_VERSION_websockets
#define MIN_VERSION_websockets(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  12 || \
  (major1) == 0 && (major2) == 12 && (minor) <= 5)
#endif /* MIN_VERSION_websockets */

/* package transformers-0.5.5.0 */
#ifndef VERSION_transformers
#define VERSION_transformers "0.5.5.0"
#endif /* VERSION_transformers */
#ifndef MIN_VERSION_transformers
#define MIN_VERSION_transformers(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  5 || \
  (major1) == 0 && (major2) == 5 && (minor) <= 5)
#endif /* MIN_VERSION_transformers */

/* package wai-3.2.1.2 */
#ifndef VERSION_wai
#define VERSION_wai "3.2.1.2"
#endif /* VERSION_wai */
#ifndef MIN_VERSION_wai
#define MIN_VERSION_wai(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 1)
#endif /* MIN_VERSION_wai */

/* package warp-3.2.25 */
#ifndef VERSION_warp
#define VERSION_warp "3.2.25"
#endif /* VERSION_warp */
#ifndef MIN_VERSION_warp
#define MIN_VERSION_warp(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  2 || \
  (major1) == 3 && (major2) == 2 && (minor) <= 25)
#endif /* MIN_VERSION_warp */

/* package file-embed-0.0.10.1 */
#ifndef VERSION_file_embed
#define VERSION_file_embed "0.0.10.1"
#endif /* VERSION_file_embed */
#ifndef MIN_VERSION_file_embed
#define MIN_VERSION_file_embed(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  0 || \
  (major1) == 0 && (major2) == 0 && (minor) <= 10)
#endif /* MIN_VERSION_file_embed */

/* package wai-websockets-3.0.1.2 */
#ifndef VERSION_wai_websockets
#define VERSION_wai_websockets "3.0.1.2"
#endif /* VERSION_wai_websockets */
#ifndef MIN_VERSION_wai_websockets
#define MIN_VERSION_wai_websockets(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  0 || \
  (major1) == 3 && (major2) == 0 && (minor) <= 1)
#endif /* MIN_VERSION_wai_websockets */

/* package wai-app-static-3.1.6.2 */
#ifndef VERSION_wai_app_static
#define VERSION_wai_app_static "3.1.6.2"
#endif /* VERSION_wai_app_static */
#ifndef MIN_VERSION_wai_app_static
#define MIN_VERSION_wai_app_static(major1,major2,minor) (\
  (major1) <  3 || \
  (major1) == 3 && (major2) <  1 || \
  (major1) == 3 && (major2) == 1 && (minor) <= 6)
#endif /* MIN_VERSION_wai_app_static */

/* package split-0.2.3.3 */
#ifndef VERSION_split
#define VERSION_split "0.2.3.3"
#endif /* VERSION_split */
#ifndef MIN_VERSION_split
#define MIN_VERSION_split(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  2 || \
  (major1) == 0 && (major2) == 2 && (minor) <= 3)
#endif /* MIN_VERSION_split */

/* tool gcc-8 */
#ifndef TOOL_VERSION_gcc
#define TOOL_VERSION_gcc "8"
#endif /* TOOL_VERSION_gcc */
#ifndef MIN_TOOL_VERSION_gcc
#define MIN_TOOL_VERSION_gcc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  0 || \
  (major1) == 8 && (major2) == 0 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_gcc */

/* tool ghc-8.4.4 */
#ifndef TOOL_VERSION_ghc
#define TOOL_VERSION_ghc "8.4.4"
#endif /* TOOL_VERSION_ghc */
#ifndef MIN_TOOL_VERSION_ghc
#define MIN_TOOL_VERSION_ghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc */

/* tool ghc-pkg-8.4.4 */
#ifndef TOOL_VERSION_ghc_pkg
#define TOOL_VERSION_ghc_pkg "8.4.4"
#endif /* TOOL_VERSION_ghc_pkg */
#ifndef MIN_TOOL_VERSION_ghc_pkg
#define MIN_TOOL_VERSION_ghc_pkg(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_ghc_pkg */

/* tool haddock-2.20.0 */
#ifndef TOOL_VERSION_haddock
#define TOOL_VERSION_haddock "2.20.0"
#endif /* TOOL_VERSION_haddock */
#ifndef MIN_TOOL_VERSION_haddock
#define MIN_TOOL_VERSION_haddock(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  20 || \
  (major1) == 2 && (major2) == 20 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_haddock */

/* tool hpc-0.67 */
#ifndef TOOL_VERSION_hpc
#define TOOL_VERSION_hpc "0.67"
#endif /* TOOL_VERSION_hpc */
#ifndef MIN_TOOL_VERSION_hpc
#define MIN_TOOL_VERSION_hpc(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  67 || \
  (major1) == 0 && (major2) == 67 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_hpc */

/* tool hsc2hs-0.68.3 */
#ifndef TOOL_VERSION_hsc2hs
#define TOOL_VERSION_hsc2hs "0.68.3"
#endif /* TOOL_VERSION_hsc2hs */
#ifndef MIN_TOOL_VERSION_hsc2hs
#define MIN_TOOL_VERSION_hsc2hs(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  68 || \
  (major1) == 0 && (major2) == 68 && (minor) <= 3)
#endif /* MIN_TOOL_VERSION_hsc2hs */

/* tool pkg-config-0.29 */
#ifndef TOOL_VERSION_pkg_config
#define TOOL_VERSION_pkg_config "0.29"
#endif /* TOOL_VERSION_pkg_config */
#ifndef MIN_TOOL_VERSION_pkg_config
#define MIN_TOOL_VERSION_pkg_config(major1,major2,minor) (\
  (major1) <  0 || \
  (major1) == 0 && (major2) <  29 || \
  (major1) == 0 && (major2) == 29 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_pkg_config */

/* tool runghc-8.4.4 */
#ifndef TOOL_VERSION_runghc
#define TOOL_VERSION_runghc "8.4.4"
#endif /* TOOL_VERSION_runghc */
#ifndef MIN_TOOL_VERSION_runghc
#define MIN_TOOL_VERSION_runghc(major1,major2,minor) (\
  (major1) <  8 || \
  (major1) == 8 && (major2) <  4 || \
  (major1) == 8 && (major2) == 4 && (minor) <= 4)
#endif /* MIN_TOOL_VERSION_runghc */

/* tool strip-2.31 */
#ifndef TOOL_VERSION_strip
#define TOOL_VERSION_strip "2.31"
#endif /* TOOL_VERSION_strip */
#ifndef MIN_TOOL_VERSION_strip
#define MIN_TOOL_VERSION_strip(major1,major2,minor) (\
  (major1) <  2 || \
  (major1) == 2 && (major2) <  31 || \
  (major1) == 2 && (major2) == 31 && (minor) <= 0)
#endif /* MIN_TOOL_VERSION_strip */

#ifndef CURRENT_COMPONENT_ID
#define CURRENT_COMPONENT_ID "score2-0.1.0.0-8xNCe2fjdsmf7pVRZbZjD-server"
#endif /* CURRENT_COMPONENT_ID */
#ifndef CURRENT_PACKAGE_VERSION
#define CURRENT_PACKAGE_VERSION "0.1.0.0"
#endif /* CURRENT_PACKAGE_VERSION */

#undef CURRENT_PACKAGE_KEY
#undef CURRENT_COMPONENT_ID
